org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

unityStreamingAssets=
unityTemplateVersion=21
unityProjectPath=/Users/mzaidaannugroho/Main/Uni/6th Semester/Pemrograman Perangkat Mobile/ARbudayaKepri/ar_budaya_kepri/unity/riau_heritage_ar
unity.projectPath=/Users/mzaidaannugroho/Main/Uni/6th Semester/Pemrograman Perangkat Mobile/ARbudayaKepri/ar_budaya_kepri/unity/riau_heritage_ar
unity.debugSymbolLevel=none
unity.buildToolsVersion=36.0.0
unity.minSdkVersion=25
unity.targetSdkVersion=36
unity.compileSdkVersion=36
unity.applicationId=com.zaidaan.riauheritagear
unity.abiFilters=armeabi-v7a,arm64-v8a
unity.versionCode=1
unity.versionName=0.1
unity.namespace=com.zaidaan.riauheritagear
unity.agpVersion=8.10.0
unity.androidSdkPath=/Applications/Unity/Hub/Editor/6000.3.0f1/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=/Applications/Unity/Hub/Editor/6000.3.0f1/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=/Applications/Unity/Hub/Editor/6000.3.0f1/PlaybackEngines/AndroidPlayer/OpenJDK
unity.javaCompatabilityVersion=VERSION_17
unity.installInBuildFolder=false
